### ISSUE TITLE
Create a key instead of using str

### ISSUE THREAD

**Issue by Curt-Park** [medipixel/rl_algorithms#116]

**Comment by MrSyee** [comment]
Currently, this issue isn't needed by using [ConfigDict](https://github.com/medipixel/rl_algorithms/blob/dd692c6eb5d439f30843669ca465f00a2fd28322/rl_algorithms/utils/config.py#L10)

ConfigDict is used as follows: https://github.com/medipixel/rl_algorithms/blob/dd692c6eb5d439f30843669ca465f00a2fd28322/rl_algorithms/dqn/agent.py#L114
