### ISSUE TITLE
Python Version

### ISSUE THREAD

**Issue by impulsecorp** [medipixel/rl_algorithms#162]
Does this program use Python 3.6? If so, why does it use NumPy for Python 2.7 (CPython 2.7 - cp27)?
----------------------------
15:27:33|peter@laptop:[rl_algorithms]> make dep                
pip install -r requirements.txt
Collecting numpy==1.16.2 (from -r requirements.txt (line 1))
  Using cached https://files.pythonhosted.org/packages/c4/33/8ec8dcdb4ede5d453047bbdbd01916dbaccdb63e98bba60989718f5f0876/numpy-1.16.2-cp27-cp27mu-manylinux1_x86_64.whl
----------------------------

**Comment by Curt-Park** [comment]
Hi.

I created a new virtual environment with python3.6 and ran the command 'make dep'.
I checked it installs numpy for python3.6.

```
pip install -r requirements.txt
Collecting numpy==1.16.2 (from -r requirements.txt (line 1))
  Downloading https://files.pythonhosted.org/packages/35/d5/4f8410ac303e690144f0a0603c4b8fd3b986feb2749c435f7cdbb288f17e/numpy-1.16.2-cp36-cp36m-manylinux1_x86_64.whl (17.3MB)
     |████████████████████████████████| 17.3MB 97.4MB/s
```

Why don't you remove the cached the numpy package?
https://stackoverflow.com/questions/9510474/removing-pips-cache

**Comment by Curt-Park** [comment]
This repository is available on python 3.6.1+.
I will add this info in README.

**Comment by jjfiv** [comment]
I was playing with this repository and was unable to get the pong example to run on python3 because **_wandb_** depends on **_pynvml_** which is only available for python2 ; it uses print statements with no parentheses -- it was crashing at the import wandb.

**Comment by Curt-Park** [comment]
@jjfiv Did you do the following steps?:

1. Create [wandb](https://www.wandb.com/) account
2. Check your **API key** in settings, and login on your terminal
`$ wandb login API_KEY`
3. Initialize wandb on your terminal
`$ wandb init`

**Comment by Curt-Park** [comment]
Sorry for the confusion. I added more information on README.
I will close this one. Please let me know if you face any other issue.
