### ISSUE TITLE
Is there any pretrained model provided?

### ISSUE THREAD

**Issue by jsrimr** [medipixel/rl_algorithms#170]
Hello, 
I'd like to use pretrained weight for the models (especially dqn.py for Pong), but I don't see one. If it exists, could you provide the link?

Thanks,

**Comment by Curt-Park** [comment]
This is the [pretrained weight](https://drive.google.com/open?id=16Jqu_0J5yCytSNqTsiGr2Q-96TbILUtE) for you, and the following command is how to run Pong with the pretrained weight.
```
python run_pong_no_frameskip_v4.py --algo dqn --load-from PongNoFrameskip-v4_dqn_821874e_ep_1440.pt --test
```

Plus, I am checking the performance on the master's latest commit (95bc6ea). I will give you the result once the training is done.

**Comment by Curt-Park** [comment]
Please see [the log](https://app.wandb.ai/medipixel_rl/pongnoframeskip-v4/runs/eigzk8a6). You can see its learning progress. 
(The log doesn't include the initial random steps, so we need to add 20 episodes from the value of x-axis.)

```
python run_pong_no_frameskip_v4.py --algo dqn --off-render --log
```

**Comment by Curt-Park** [comment]
If you still have any problem, please reopen the issue.

**Comment by jsrimr** [comment]
> If you still have any problem, please reopen the issue.

Thanks for your kind reply! However, I don't think I have the right to reopen the issue.
I made conda environment and executed "make dep" but failing in rendering. I additionally installed 'gym[atari]' but still fails. Is requirements.txt enough for full execution? Could you give any advice?
I'm using OSX.

Thanks a lot for providing so valuable repo!

**Comment by Curt-Park** [comment]
Have you tried this?
https://medium.com/@xueguang.lu/install-openai-gym-with-atari-on-macos-cd35d09194ee

**Comment by jsrimr** [comment]
> Have you tried this?
> https://medium.com/@xueguang.lu/install-openai-gym-with-atari-on-macos-cd35d09194ee

물론입니다, 선생님. 따옴표까지 잘 붙여서 설치했죠! pip install 'gym[atari]'
설치도 잘 됐구요

일단은 알고리즘 구현체 보는게 목표였으니까 그 부분을 중심으로 열심히 연구해보겠습니다!

페이스북에 보니 연구성과를 저널에 내는 과정중에 있다고 하셨는데 정말 축하드립니다! 그냥 저널내서 축하드리는 게 아니라 깜깜한 마음을 다 이기고 남들이 안된다는 연구에서 결과 낸 과정을 축하드립니다!

제가 지금 강화학습 프로젝트를 하는데 선생님보다 훨씬 수준 낮은 연구임에도 어깨가 무겁고 마음이 깜깜한데 저도 선생님처럼 극복해내고 싶습니다

**Comment by Curt-Park** [comment]
@jsrimr 응원의 말씀 감사합니다.
앞으로의 성과를 서로 공유하고 그로써 서로에게 좋은 영감이 될 수 있는 관계가 된다면 좋겠습니다.
저도 정섭님을 응원하겠습니다. 

감사합니다.
박진우 드림

**Comment by MrSyee** [comment]
@jsrimr 응원 감사합니다!
이렇게 응원해주시니 더 힘이 나네요. 하시는 연구도 충분히 의미있는 연구인 것 같습니다. 잘 진행하셔서 원하시는 성과 얻으셨으면 좋겠습니다.
저도 항상 응원합니다.

감사합니다.
김경환 드림
