### ISSUE TITLE
gym[atari] isn't installed by `make dep`

### ISSUE THREAD

**Issue by mclearning2** [medipixel/rl_algorithms#174]
In my case(zsh shell), `pip install gym[atari]` doesn't work. But atari-py is fine. So please check it and replace `gym[atari]` to `atari-py` in `requirements.txt

```
numpy==1.16.2
torch==1.0.1
gym
gym[atari] <====== THIS DOESN'T WORK
box2d-py
scipy
typing
cloudpickle
opencv-python
wandb
```

**Comment by MrSyee** [comment]
It was modified in #239.
