### ISSUE TITLE
Automatically set value of fc_input_size in pong_no_frameskip_v4/dqn

### ISSUE THREAD

**Issue by mclearning2** [medipixel/rl_algorithms#176]
The fully connected layer size of DQN in Atari environment is manually set by someone. I suggest to use a dummy input and automatically the size of CNN output.
```
def get_cnn_model():
        fc_input_size = 3136
        hidden_sizes = [512]
        action_dim = env.action_space.n
...
```

**Comment by MrSyee** [comment]
Completed in #192.
