### ISSUE TITLE
There is no use lambda for gae in ppo

### ISSUE THREAD

**Issue by mclearning2** [medipixel/rl_algorithms#179]
In `update_model()` function in PPO Agent. There is no use hyperparameter 'LAMBDA', it just  use default value `tau = 0.95`

```
returns = ppo_utils.compute_gae(
            next_value, self.rewards, self.masks, self.values
        )
```

**Comment by MrSyee** [comment]
Completed in #184.
https://github.com/medipixel/rl_algorithms/blob/dd692c6eb5d439f30843669ca465f00a2fd28322/rl_algorithms/ppo/agent.py#L175-L182
