### ISSUE TITLE
hi, does this version of dqn implement n-step learning?

### ISSUE THREAD

**Issue by junhuang-ifast** [medipixel/rl_algorithms#187]
https://github.com/medipixel/rl_algorithms/blob/master/rl_algorithms/dqn/agent.py

**Comment by MrSyee** [comment]
Hi. @junhuang-ifast

We implement Rainbow DQN includes n-step learning in the repository. We use n-step buffer which has n-step return and transition for calculating both 1-step and n-step loss.
See this part:
- n-step buffer: https://github.com/medipixel/rl_algorithms/blob/e20f61649dc904f9b7e647b5f47d3c82b2b38d29/rl_algorithms/dqn/agent.py#L117
- n-step DQN loss: https://github.com/medipixel/rl_algorithms/blob/e20f61649dc904f9b7e647b5f47d3c82b2b38d29/rl_algorithms/dqn/agent.py#L271

Thank you.
