### ISSUE TITLE
understanding IQN config params

### ISSUE THREAD

**Issue by junhuang-ifast** [medipixel/rl_algorithms#190]
Hi, im trying to understand how to use RainbowIQN and came a cross the [IQN config params](https://github.com/medipixel/rl_algorithms/blob/e20f61649dc904f9b7e647b5f47d3c82b2b38d29/configs/pong_no_frameskip_v4/dqn.py#L24). I've read the [IQN paper](https://arxiv.org/pdf/1806.06923.pdf) but im still having trouble understanding each params intuitively.

Any help on understanding these params, specifically:

n_tau_samples=64,
n_tau_prime_samples=64,
n_quantile_samples=32, (just acts as a backup tau param in the case n_tau_samples=0?, based on [code](https://github.com/medipixel/rl_algorithms/blob/e20f61649dc904f9b7e647b5f47d3c82b2b38d29/rl_algorithms/dqn/networks.py#L254))
quantile_embedding_dim=64,

(and what is expected by adjusting them) would be appreciated thanks :)

**Comment by MrSyee** [comment]
I'm sorry to reply late.
We just choose this config according to Figure2 on IQN paper.
![image](https://user-images.githubusercontent.com/17582508/79940854-d49cd000-849d-11ea-83bb-8c4b0f62a6f7.png)
Decisively [Google Dopamine](https://github.com/google/dopamine/blob/e7d780d7c80954b7c396d984325002d60557f7d1/dopamine/agents/implicit_quantile/configs/implicit_quantile.gin#L12) which we referred to use this config.

And n_tau_samples can be None value. When it has None, n_tau_samples is same n_quantile_samples.

Thank you.
