### ISSUE TITLE
Test all contributors

### ISSUE THREAD

**Issue by medipixel** [medipixel/rl_algorithms#193]
@all-contributors please add @minseop4898 for code

**Comment by medipixel** [comment]
@all-contributors please add @minseop4898 for code

**Comment by MrSyee** [comment]
@all-contributors please add @minseop4898 for code

**Comment by medipixel** [comment]
@all-contributors please add @minseop4898 for code

**Comment by MrSyee** [comment]
@all-contributors please add @minseop4898 for code

**Comment by MrSyee** [comment]
@all-contributors please add @minseop4898 for code

**Comment by medipixel** [comment]
@all-contributors please add @MrSyee for code

**Comment by medipixel** [comment]
@all-contributors please add @MrSyee for code
