### ISSUE TITLE
Any support for other Atari environments

### ISSUE THREAD

**Issue by TonyLianLong** [medipixel/rl_algorithms#305]
After changing environment to `Assault`, the algorithm no longer works, unlike other implementations. Is there any plan for supporting other environments in Atari?

**Comment by MrSyee** [comment]
Hi, @TonyLianLong 

There are no plans to verify all other Atari environment besides Pong yet. But, our algorithm will perform well enough in other environments if you tune the parameters properly. In our research, it shows a good performance in our own environment.

If you find a bug in use, let me know. I hope you make a good result.

**Comment by TonyLianLong** [comment]
Thanks for quick response. Is there any advice on what hyperparams to tune?

**Comment by MrSyee** [comment]
In my experience, when using Rainbow, it is important to adjust replay buffer parameter depending on your machine and environment. If you use C51, you should set v_min, v_max, atom_size depending on reward scale of environment. For exploration, if you don't use noisynet, epsilon parameters are also important.

**Comment by TonyLianLong** [comment]
Thanks for the useful response. If you have time, I suggest you have a look at `Assault` since it is weird that while other code bases achieve about 400 reward in 100k, this implementation with IQN achieves only about random in this Atari environment.
