### ISSUE TITLE
Citation for Usage

### ISSUE THREAD

**Issue by krishanrana** [medipixel/rl_algorithms#306]
Hi, I am a Deep RL researcher at QUT in Australia and would like to use your demonstrations code for benchmarking some experiments in my paper. Please could you add BibTex citation to your ReadMe so that I may cite your code implementations which I will be using. Thank you! Great work with your code base so far, and thank you for making it public!

**Comment by MrSyee** [comment]
Hi. @krishanrana!
I'm very glad to hear that our repository is cited in your paper. I add BibTex citation (#307).
I hope you finish your work well!
