### ISSUE TITLE
Reprise RainbowIQN or IQN for PongNoFrameskip-v4

### ISSUE THREAD

**Issue by pytorchinfo** [medipixel/rl_algorithms#311]
I notice that there was an amazing result that used RainbowIQN (as well as plain IQN) to accomplishes the perfect score (21) for the environment `PongNoFrameskip-v4`. Thanks for this amazing result.

Unfortunately, I do not know how to reprise this results. Could the latest repo support such training? If not, what command as well what version of this repo need to be used to reprise the result? Thanks!

@Curt-Park

**Comment by jinPrelude** [comment]
Hi @pytorchinfo. Thanks for using our repo!
The current default setting for `PongNoFrameskip-v4` is RainbowIQN, so you can reproduce the result by running the command `python run_pong_no_frameskip_v4.py --off-render`.
And we just checked the default setting of the current master branch and it successfully gained the perfect score on our computer in `PongNoFrameskip-v4` environment.
So if you're still getting struggled with this problem, we recommend you to recreate the new virtual environment and re-install the requirements by using `make dev` or `make dep`, and than run `python run_pong_no_frameskip_v4.py --off-render`. 
Feel free to ask questions and let us know if you solved the problem. Thanks!

**Comment by pytorchinfo** [comment]
@jinPrelude   Thanks for your prompt reply and useful information. I used the command you provided, and it indeed works.
